---
- name: Apacheをインストール
  yum: name=httpd-2.2.15 state=latest

- name: DocumentRoot変更
  replace:
    dest=/etc/httpd/conf/httpd.conf
    regexp='^DocumentRoot "/var/www/html"'
    replace='DocumentRoot "{{ apache_document_root }}"'

- name: ServerSignatureコメントアウト（サーバー情報を隠匿）
  replace:
    dest=/etc/httpd/conf/httpd.conf
    regexp='^ServerSignature On'
    replace='# ServerSignature On'

- name: ファイル一覧表示しない
  replace:
    dest=/etc/httpd/conf/httpd.conf
    regexp='Options Indexes FollowSymLinks'
    replace='Options -Indexes FollowSymLinks'

- name: .htaccessを有効にする
  replace:
    dest=/etc/httpd/conf/httpd.conf
    regexp='AllowOverride None'
    replace='AllowOverride All'

- name: DocumentRoot作成
  file:
    path={{ apache_document_root }}
    owner=apache
    group=apache
    mode=0775
    state=directory