---
- name: EPELリポジトリをインストール
  yum: name=epel-release state=present
  tags:
    - php

- name: EPEL設定ファイル1
  replace: >
    dest=/etc/yum.repos.d/epel.repo
    regexp="^#baseurl="
    replace="baseurl="
  tags:
    - php

- name: EPEL設定ファイル2
  replace: >
    dest=/etc/yum.repos.d/epel.repo
    regexp="^mirrorlist="
    replace="#mirrorlist="
  tags:
    - php

- name: Remiリポジトリがインストール済か
  shell: rpm -q remi-release
  register: remi_release_status
  failed_when: False
  changed_when: False
  tags:
    - php

- name: Remiリポジトリをインストール
  yum: name="http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
  when: remi_release_status|failed
  tags:
    - php

- name: PHP 5.3をインストール
  yum: name={{ item }} state=present
  with_items:
    - php-5.3.3
    - php-cli
    - php-common
    - php-devel
    - php-gd
    - php-imap
    - php-json
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-pdo
    - php-pear
    - php-pecl-apc
    - php-pecl-apc-devel
    - php-pecl-memcached
    - php-pecl-zip
    - php-pgsql
    - php-process
    - php-xml
  notify:
    - Apacheを再起動
  tags:
    - php

- name: PHPをタイムゾーンの設定
  replace: >
    dest=/etc/php.ini
    regexp="^;date\.timezone ="
    replace="date.timezone = Asia/Tokyo"
  tags:
    - php

- name: 文字コード
  replace: >
    dest=/etc/php.ini
    regexp='^;default_charset = "iso-8859-1"'
    replace='default_charset = "UTF-8"'
  tags:
    - php

- name: PHPのバージョン情報隠匿
  replace: >
    dest=/etc/php.ini
    regexp="^expose_php = On"
    replace="expose_php = Off"
  tags:
    - php

- name: mbstring.language
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.language = Japanese"
    replace="mbstring.language = Japanese"
  tags:
    - php

- name: mbstring.internal_encoding
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.internal_encoding = EUC-JP"
    replace="mbstring.internal_encoding = UTF-8"
  tags:
    - php

- name: mbstring.encoding_translation
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.encoding_translation = Off"
    replace="mbstring.encoding_translation = Off"
  tags:
    - php

- name: mbstring.http_input
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.http_input = auto"
    replace="mbstring.http_input = pass"
  tags:
    - php

- name: mbstring.http_output
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.http_output = SJIS"
    replace="mbstring.http_output = pass"
  tags:
    - php

- name: mbstring.detect_order
  replace: >
    dest=/etc/php.ini
    regexp="^;mbstring.detect_order = auto"
    replace="mbstring.detect_order = UTF-8,SJIS,EUC-JP,JIS,ASCII"
  tags:
    - php